name: Check certificates to be PEM encoded

on:
  pull_request:
    branches: [ "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check certificates to be PEM encoded
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.cer
            **.der
            **.pem

      - name: Check PEM encoding
        env:    
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          fail=false
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            openssl x509 -noout -in $file
            if [[ $? -ne 0 ]]
              then 
                echo "File is not PEM encoded."
                fail=true
            fi
          done        
          if [[ $fail -eq true ]]
            then
              echo "At least one certificate was not PEM encoded."
              #exit 1
          fi

      - name: Check file name and location
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        shell: pwsh
        run: |
          fail=false
          foreach ($changedFile in ${ALL_CHANGED_FILES}) {
            echo "$file was changed"
            $bytes = [System.IO.File]::ReadAllBytes($file)
            $cert = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($bytes)
            $dn = [X500DistinguishedName]::new($cert.Subject)
            try {
              $cn = ($dn.Format($true).Split([Environment]::NewLine, [StringSplitOptions]::RemoveEmptyEntries) | Where-Object {$_ -match 'CN='}).Split('=')[1]
            } catch {
              $o = ($dn.Format($true).Split([Environment]::NewLine, [StringSplitOptions]::RemoveEmptyEntries) | Where-Object {$_ -match 'O='}).Split('=')[1]
              $cn = $o
            }
            $o = ($dn.Format($true).Split([Environment]::NewLine, [StringSplitOptions]::RemoveEmptyEntries) | Where-Object {$_ -match 'O='}).Split('=')[1]
            $oTemp = $o.Replace(' ','_')
            $oTemp2 = $otemp.Replace('"','')
            $org = $oTemp2.Split([IO.Path]::GetInvalidFileNameChars()) -join '-'
            $filenameTemp = "$($cn.Replace(' ','_'))_$($cert.Thumbprint).der"
            $filenameTemp2 = $filenameTemp.Replace('"','')
            $filename = $filenameTemp2.Split([IO.Path]::GetInvalidFileNameChars()) -join '-'
            $year = $cert.NotBefore.Year
            if ($cert.Issuer -eq $cert.Subject) {
                if ($changedFile -eq "roots\$org\$year\$filename") {
                  echo "file match"
                }
            } else {
                if ($changedFile -eq "intermediaries\$org\$year\$filename") {
                  echo "file match"
                }
            }        
          }  
