# This workflow is used to create new releases.
# It creates a ZIP and P7B bundle of the CER files and generates a proper release description.

name: Create Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number. (e.x.: 2024-02-04)'
        required: true

# set a custom name for the action view
run-name: Create Release - ${{ inputs.version }}        

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Get repo 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ZIP certificates
        run: |
          # Create ZIP archive
          cd $GITHUB_WORKSPACE
          zip -r NoSpamProxy_CA_Bundle-${{ inputs.version }}.zip roots intermediaries -i *.cer

      - name: Create P7B certificate bundle
        run: |
          # create P7B bundle
          cd $GITHUB_WORKSPACE
          certFiles=();for file in $(find ~+ -iname "*.cer");  do echo ${file}; certFiles+=(-certfile ${file}); done;
          openssl crl2pkcs7 -nocrl "${certFiles[@]}" -outform DER -out NoSpamProxy_CA_Bundle-${{ inputs.version }}.p7b

      - name: Get previous release tag
        id: get-tag
        run: |
          # get previous release tag
          PREVIOUS_TAG=$(git tag --sort=-v:refname | head -n 2 | tail -n 1)
          echo "prev tag: $PREVIOUS_TAG"
          echo "prev_tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT  

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ steps.get-tag.outputs.prev_tag }}
          sha: ${{ github.event.workflow_run.head_branch }}
          files: |
            **.cer  

      - name: Create release description
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          DELETED_FILES: ${{ steps.changed-files-specific.outputs.deleted_files }}
        run: |
          # create release description
          cd $GITHUB_WORKSPACE
          
          echo "# Added certificates:" >> ReleaseNotes.md
          if [[ -z "${ADDED_FILES}" ]]
          then
            echo "No certificates added in this release." >> ReleaseNotes.md
          else
            for file in ${ADDED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

          echo "# Deleted certificates:" >> ReleaseNotes.md
          if [[ -z "${ADDED_FILES}" ]]
          then
            echo "No certificates deleted in this release." >> ReleaseNotes.md
          else
            for file in ${DELETED_FILES}; do
              echo "- $file  " >> ReleaseNotes.md
            done
          fi

      - name: Create release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ inputs.version }}
          artifacts: "NoSpamProxy_CA_Bundle-${{ inputs.version }}.zip,NoSpamProxy_CA_Bundle-${{ inputs.version }}.p7b"
          bodyFile: "ReleaseNotes.md"